# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: npm testing

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  newversions:
    strategy:
      fail-fast: false
      matrix:
        npmver:
        - "11"
        - "10"
        - "9"
        - "8"
        - "7"
        - "6"
        - "5"
        - "4"
        - "3"
        - "2"

    runs-on: ubuntu-latest
    env:
      WORK: ${{ matrix.npmver }}

    steps:
    - uses: actions/checkout@v4
    - name: Install npm
      run: sudo npm install -g npm@$WORK
    - name: Does the envvar work at all?
      run: npm_config_prefix=foo npm config ls -l | grep prefix -i
    - name: Test it
      run: npm_config_prefix=foo npm run bar
  oldversions:
    strategy:
      fail-fast: false
      matrix:
        npmver:
        - "npm@1"
        - "npm@1.1"
        - "git://github.com/npm/cli.git#v0.3.18"
        - "git://github.com/npm/cli.git#v0.2.13"

    runs-on: ubuntu-latest
    env:
      WORK: ${{ matrix.npmver }}

    steps:
    - uses: actions/checkout@v4
    - name: Install npm
      run: sudo npm install -g $WORK

    - name: Setup up ancient nodejs
      uses: actions/setup-node@v3.9.1
      with:
        node-version: 8
    - name: Does the envvar work at all?
      run: npm_config_prefix=foo npm config ls -l | grep prefix -i
    - name: Test it
      run: npm_config_prefix=foo npm run bar

