# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
     pyver:
       type: choice
       options:
         - "3.8"
         - "3.9"
         - "3.10"
         - "3.11"
         - "3.12"
       default: "3.11"
       required: true
       description: Python version

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-20.04, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.pyver }}
    - name: Install dependencies
      run: |
        pip install --extra-index-url https://gitlab.com/api/v4/projects/19904939/packages/pypi/simple pythonfuzz
    - name: Run the code
      run: |
        python run.py
